### ISSUE TITLE
Interested in an up-to-date, tested version?

### ISSUE THREAD

**Issue by purohit** [CellProfiler/docker#11]
Hello,

At Recursion we've developed an updated, fully-tested version of CellProfiler's Docker from 2.2.0 that also solves the zombie reaping problem. I've tested it in both batch and GUI mode and it works great. I also have a branch open for alpine development since the base is Ubuntu 16.04 and therefore likely much larger than necessary.

Are you interested in a pull request?

**Comment by karhohs** [comment]
I am interested in seeing the changes you've made.

**Comment by AnneCarpenter** [comment]
Neat! Does it replace this one? Not sure what happened to it: https://github.com/CellProfiler/docker/pull/5

**Comment by purohit** [comment]
@AnneCarpenter Yep, it replaces that pull request. I think it was forgotten for about a year so it's out of date and can be closed. I'll open a new one in a second here.

**Comment by 0x00b1** [comment]
Updated
