### ISSUE TITLE
Zombie cellprofiler processes in docker container (fix included)

### ISSUE THREAD

**Issue by jd-recursion** [CellProfiler/docker#6]
Hi all,

We routinely run ~10,000 headless instances of Cellprofiler in parallel on AWS.  Thank you guys for creating a docker image!  It's the one we've been using.

In about 1 / 1000 runs the docker container would not exit cleanly.  We determined that it was likely the [docker zombie reaping problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/).  In short, there were subprocesses in the container that were dead but weren't being cleaned up.

Fortunately, phusion solved this problem and created [phusion/baseimage](https://github.com/phusion/baseimage-docker). Their image has a lighweight `my_init` script which detects and kill zombies.  We rebuilt the CellProfiler docker image using phusion/baseimage as the starting point, and haven't seen any zombies with the new image.

The [fix](https://github.com/recursionpharma/docker/pull/1/files) is just a 2 line change.  If you think this would be useful, I can create a PR.

-- JD

**Comment by jdeveloperw** [comment]
Feel free to close this issue.
